syntax = "proto3";

option java_multiple_files = true;
option java_package = "generated.grpc.smartassessment";
option java_outer_classname = "SmartAssessmentServiceImpl";

package SmartAssessmentGrpc;

// the SmartAssessmentService manages digital examinations,grading and integrity monitoring.

service SmartAssessmentService {

  // UNARY (SIMPLE RPC)
  // retrieves details about a specific assessment.
  rpc GetAssessmentDetails(AssessmentRequest) 
      returns (AssessmentInfo) {}

  // CLIENT STREAMING
  //streams multiple answers from a student exam submission and returns a final submission summary.
  rpc SubmitAssessmentAnswers(stream AnswerSubmission) 
      returns (SubmissionSummary) {}

  // SERVER STREAMING
  //streams assessment results for administrative review.
  rpc StreamAssessmentResults(ResultRequest) 
      returns (stream StudentResult) {}

  // BIDIRECTIONAL STREAMING
  //enables real-time exam monitoring and alert responses.
  rpc LiveAssessmentMonitoring(stream StudentActivity) 
      returns (stream MonitoringAlert) {}
}

// request for assessment details
message AssessmentRequest {
  string assessmentId = 1;
}

// response containing assessment information
message AssessmentInfo {
  string subject = 1;
  int32 durationMinutes = 2;
}

//message representing a student's answer submission
message AnswerSubmission {
  string questionId = 1;
  string answerText = 2;
}

// final submission summary
message SubmissionSummary {
  double totalScore = 1;
}

// request to stream results
message ResultRequest {
  string assessmentId = 1;
}

// result message per student
message StudentResult {
  string studentId = 1;
  double score = 2;
}

//activity message during monitoring
message StudentActivity {
  string activityType = 1;
  string timestamp = 2;
}

// alert response from monitoring system
message MonitoringAlert {
  string alertMessage = 1;
}

