syntax = "proto3";

option java_multiple_files = true;
option java_package = "generated.grpc.smartclassroom";
option java_outer_classname = "SmartClassroomServiceImpl";

package SmartClassroomGrpc;

// the SmartClassroomService manages intelligent classroom operations. It simulates attendance collection and real-time lecture interaction.

service SmartClassroomService {

  // CLIENT STREAMING
  //streams multiple attendance records from a classroom scanner and returns a summary once all students have been marked present.
  rpc UploadAttendanceRecords(stream AttendanceRecord) returns (AttendanceSummary) {}

  // BIDIRECTIONAL STREAMING
  //enables real-time communication between students and lecturer during a live class session.
  rpc LiveClassInteraction(stream StudentQuestion) returns (stream LecturerReply) {}

}

// message representing a student attendance record
message AttendanceRecord {
  string studentId = 1;
  string timestamp = 2;
}

//summary response after attendance upload
message AttendanceSummary {
  int32 totalStudentsMarked = 1;
}

// message sent by student during live session
message StudentQuestion {
  string studentId = 1;
  string questionText = 2;
}

// response from lecturer
message LecturerReply {
  string responseText = 1;
}

